version: "3.9"

services:
  app:
    build: .
    ports: 
			- "3000":"3000"
    volumes: 
  	  - .:"/usr/src"
      - /usr/src/node_modules
    environment: 
      MONGO_URI: "mongodb://db:27017/mascotaDB"
    depends_on: 
      - db 
            
  db:
  	image: mongo        